// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wheel_wise.Data;

#nullable disable

namespace wheel_wise.Migrations
{
    [DbContext(typeof(WheelWiseContext))]
    [Migration("20240426084057_FixedMigrationIssue")]
    partial class FixedMigrationIssue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvertisementUser", b =>
                {
                    b.Property<int>("FavoriteAdvertisementsId")
                        .HasColumnType("int");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.HasKey("FavoriteAdvertisementsId", "User1Id");

                    b.HasIndex("User1Id");

                    b.ToTable("AdvertisementUser");
                });

            modelBuilder.Entity("CarEquipment", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentsId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "EquipmentsId");

                    b.HasIndex("EquipmentsId");

                    b.ToTable("CarEquipment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("wheel_wise.Model.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7509),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7555),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7558),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7561),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7563),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7566),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7571),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7574),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7577),
                            Description = "description",
                            Highlighted = true,
                            Title = "title"
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7580),
                            Description = "description",
                            Highlighted = true,
                            Title = "title"
                        },
                        new
                        {
                            Id = 11,
                            CarId = 11,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7583),
                            Description = "description",
                            Highlighted = true,
                            Title = "title"
                        },
                        new
                        {
                            Id = 12,
                            CarId = 12,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7586),
                            Description = "description",
                            Highlighted = true,
                            Title = "title"
                        },
                        new
                        {
                            Id = 13,
                            CarId = 13,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7590),
                            Description = "description",
                            Highlighted = true,
                            Title = "title"
                        },
                        new
                        {
                            Id = 14,
                            CarId = 14,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7592),
                            Description = "description",
                            Highlighted = true,
                            Title = "title"
                        },
                        new
                        {
                            Id = 15,
                            CarId = 15,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7594),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 16,
                            CarId = 16,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7596),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 17,
                            CarId = 17,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7599),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 18,
                            CarId = 18,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7601),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        },
                        new
                        {
                            Id = 19,
                            CarId = 19,
                            CreatedAt = new DateTime(2024, 4, 26, 10, 40, 57, 127, DateTimeKind.Local).AddTicks(7603),
                            Description = "description",
                            Highlighted = false,
                            Title = "title"
                        });
                });

            modelBuilder.Entity("wheel_wise.Model.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("ColorId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("TransmissionId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarTypeId = 1,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 15000,
                            Power = 100,
                            Price = 20000m,
                            Status = 1,
                            TransmissionId = 1,
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            CarTypeId = 2,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 15000,
                            Power = 100,
                            Price = 20000m,
                            Status = 2,
                            TransmissionId = 2,
                            Year = 2010
                        },
                        new
                        {
                            Id = 3,
                            CarTypeId = 3,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 18000,
                            Power = 120,
                            Price = 25000m,
                            Status = 1,
                            TransmissionId = 1,
                            Year = 2012
                        },
                        new
                        {
                            Id = 4,
                            CarTypeId = 4,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 20000,
                            Power = 140,
                            Price = 30000m,
                            Status = 2,
                            TransmissionId = 2,
                            Year = 2015
                        },
                        new
                        {
                            Id = 5,
                            CarTypeId = 5,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 15000,
                            Power = 160,
                            Price = 35000m,
                            Status = 1,
                            TransmissionId = 1,
                            Year = 2018
                        },
                        new
                        {
                            Id = 6,
                            CarTypeId = 6,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 10000,
                            Power = 180,
                            Price = 40000m,
                            Status = 0,
                            TransmissionId = 2,
                            Year = 2020
                        },
                        new
                        {
                            Id = 7,
                            CarTypeId = 7,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 22000,
                            Power = 150,
                            Price = 32000m,
                            Status = 1,
                            TransmissionId = 1,
                            Year = 2016
                        },
                        new
                        {
                            Id = 8,
                            CarTypeId = 8,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 19000,
                            Power = 130,
                            Price = 28000m,
                            Status = 1,
                            TransmissionId = 2,
                            Year = 2014
                        },
                        new
                        {
                            Id = 9,
                            CarTypeId = 9,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 17000,
                            Power = 170,
                            Price = 33000m,
                            Status = 1,
                            TransmissionId = 1,
                            Year = 2017
                        },
                        new
                        {
                            Id = 10,
                            CarTypeId = 10,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 14000,
                            Power = 190,
                            Price = 37000m,
                            Status = 0,
                            TransmissionId = 2,
                            Year = 2019
                        },
                        new
                        {
                            Id = 11,
                            CarTypeId = 11,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 21000,
                            Power = 140,
                            Price = 26000m,
                            Status = 0,
                            TransmissionId = 1,
                            Year = 2013
                        },
                        new
                        {
                            Id = 12,
                            CarTypeId = 12,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 18000,
                            Power = 160,
                            Price = 32000m,
                            Status = 0,
                            TransmissionId = 2,
                            Year = 2016
                        },
                        new
                        {
                            Id = 13,
                            CarTypeId = 13,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 20000,
                            Power = 170,
                            Price = 33000m,
                            Status = 0,
                            TransmissionId = 1,
                            Year = 2017
                        },
                        new
                        {
                            Id = 14,
                            CarTypeId = 14,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 18000,
                            Power = 150,
                            Price = 30000m,
                            Status = 0,
                            TransmissionId = 2,
                            Year = 2015
                        },
                        new
                        {
                            Id = 15,
                            CarTypeId = 15,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 15000,
                            Power = 170,
                            Price = 35000m,
                            Status = 0,
                            TransmissionId = 1,
                            Year = 2018
                        },
                        new
                        {
                            Id = 16,
                            CarTypeId = 16,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 12000,
                            Power = 190,
                            Price = 37000m,
                            Status = 0,
                            TransmissionId = 2,
                            Year = 2019
                        },
                        new
                        {
                            Id = 17,
                            CarTypeId = 17,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 19000,
                            Power = 140,
                            Price = 28000m,
                            Status = 0,
                            TransmissionId = 1,
                            Year = 2014
                        },
                        new
                        {
                            Id = 18,
                            CarTypeId = 18,
                            ColorId = 2,
                            FuelTypeId = 2,
                            Mileage = 18000,
                            Power = 160,
                            Price = 32000m,
                            Status = 0,
                            TransmissionId = 2,
                            Year = 2016
                        },
                        new
                        {
                            Id = 19,
                            CarTypeId = 19,
                            ColorId = 1,
                            FuelTypeId = 1,
                            Mileage = 20000,
                            Power = 170,
                            Price = 33000m,
                            Status = 0,
                            TransmissionId = 1,
                            Year = 2017
                        });
                });

            modelBuilder.Entity("wheel_wise.Model.CarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Opel",
                            Model = "Astra"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Renault",
                            Model = "Clio"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ford",
                            Model = "Fiesta"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Toyota",
                            Model = "Corolla"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Volkswagen",
                            Model = "Golf"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "BMW",
                            Model = "3 Series"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Mercedes-Benz",
                            Model = "C-Class"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Audi",
                            Model = "A3"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Honda",
                            Model = "Civic"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Hyundai",
                            Model = "i30"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Kia",
                            Model = "Rio"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Mazda",
                            Model = "3"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Nissan",
                            Model = "Micra"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Peugeot",
                            Model = "208"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Subaru",
                            Model = "Impreza"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Suzuki",
                            Model = "Swift"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Tesla",
                            Model = "Model 3"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Volvo",
                            Model = "V40"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Fiat",
                            Model = "500"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Skoda",
                            Model = "Octavia"
                        });
                });

            modelBuilder.Entity("wheel_wise.Model.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "White"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Black"
                        });
                });

            modelBuilder.Entity("wheel_wise.Model.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AC",
                            Type = "Technical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SeatHeating",
                            Type = "Comfort"
                        });
                });

            modelBuilder.Entity("wheel_wise.Model.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Petrol"
                        });
                });

            modelBuilder.Entity("wheel_wise.Model.Transmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transmissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Automatic"
                        });
                });

            modelBuilder.Entity("wheel_wise.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdvertisementUser", b =>
                {
                    b.HasOne("wheel_wise.Model.Advertisement", null)
                        .WithMany()
                        .HasForeignKey("FavoriteAdvertisementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wheel_wise.Model.User", null)
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarEquipment", b =>
                {
                    b.HasOne("wheel_wise.Model.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wheel_wise.Model.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wheel_wise.Model.Advertisement", b =>
                {
                    b.HasOne("wheel_wise.Model.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wheel_wise.Model.User", "User")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserId");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wheel_wise.Model.Car", b =>
                {
                    b.HasOne("wheel_wise.Model.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wheel_wise.Model.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wheel_wise.Model.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wheel_wise.Model.Transmission", "Transmission")
                        .WithMany()
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarType");

                    b.Navigation("Color");

                    b.Navigation("FuelType");

                    b.Navigation("Transmission");
                });

            modelBuilder.Entity("wheel_wise.Model.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("wheel_wise.Model.User", b =>
                {
                    b.Navigation("Advertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
